name: dart_serve_testing
description: A Rewo API project
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  rewo:
    git:
      url: https://github.com/passblock11/Rewo.git
      ref: v1.0.11
  crypto: ^3.0.6
  postgres: ^3.4.5
  path: ^1.9.1

dev_dependencies:
  http: ^1.2.2
  lints: ^4.0.0
  test: ^1.25.8
